import React from "react";
import Image from "next/image";
import globes from "../assets/globes.png";
import { useInView } from "react-intersection-observer";
import { useAnimation } from "framer-motion";
import { motion } from "framer-motion";
import { useEffect } from "react";
function Section3() {
  const { ref, inView } = useInView({
    threshold: 0.2,
  });
  const anime = useAnimation();
  const lAnime = useAnimation();

  useEffect(() => {
    if (inView) {
      anime.start({
        x: 0,
        transition: {
          type: "spring",
          duration: 1,
          bounce: 0,
        },
      });
      lAnime.start({
        x: 0,
        transition: {
          type: "spring",
          duration: 1,
          bounce: 0,
        },
      });
    }
    if (!inView) {
      anime.start({
        x: "100vw",
      });
      lAnime.start({
        x: "-100vw",
      });
    }
  }, [inView]);
  return (
    <>
      <div
        ref={ref}
        className="bg-vid flex lg:pt-0  flex-col lg:flex-row lg:space-x-8 lg:justify-center justify-between items-center   w-screen lg:h-screen h-[160vh]"
      >
        {/* main red box */}

        {/* glass yellow box */}
        {/* {//45%% width} */}
        <motion.div
          animate={lAnime}
          className="flex rounded-lg bg-glass text-white flex-col  justify-evenly items-start px-14  lg:w-[45%] w-[90%]	 h-[613px]"
        >
          <h1 className="lg:text-[45px] text-3xl ">
            Introducing Streamer Token
          </h1>
          <h2 className="lg:text-[24px] text-xl">
            Every streamer mints 11.3 millions of his personal streamer tokens
            and viewers are able to access streamer tokens on Neebmle-swap
            <br />
            <br />
            Token utility and values are measured by: revenue generated by the
            streamer, hours of watched streams, # of unique viewers, followers
            etc.
          </h2>

          <div className="space-x-8 w-full flex ">
            <button className="rounded py-2 px-4 lg:text-lg text-sm border-2 border-white">
              More on this in Neemble Whitepaper
            </button>
            <button className="rounded bg-[#0E491E] py-2 px-5 text-sm lg:text-lg border-[3px]  border-[#33BD27]">
              Buy NMBL
            </button>
          </div>
        </motion.div>

        {/* glass box */}

        {/* image box */}

        {/* {//50%% width} */}
        <motion.div animate={anime} className="lg:w-2/4 w-full  h-[640px] ">
          <Image src={globes} />
        </motion.div>

        {/* image box */}
      </div>
    </>
  );
}

export default Section3;
