import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Section1 from "../sections/Section1";
import globes from "../assets/globes.png";
import cardImage from "../assets/cards.png";
import gameTeam from "../assets/gameteams.png";
import promo1 from "../assets/promo1.png";
import promo2 from "../assets/promo2.png";
import apple from "../assets/appStore.png";
import google from "../assets/googlePlay.png";
import fVid from "../assets/videos/first.gif";

export default function Home() {
  return (
    <>
      <Navbar />
      <Section1 />
      <div className="py-24 bg-vid flex justify-evenly w-screen">
        <div className=" flex justify-center items-center w-1/2 h-96">
          <div className="rounded-md px-12 py-5 bg-glass border-2 border-cyan-700">
            <div className=" text-white py-14 px-14">
              <h1 className="pb-8 text-2xl">
                New Era Of Game Streaming is here
              </h1>
              <p className="text-center text-lg">
                The Ultimate blockchain watch to earn <br /> & stream to earn
                platform
              </p>
              <div className="pt-8 flex justify-center items-center space-x-14">
                <button className="link rounded-md border-2 border-cyan-700 px-2 py-2">
                  Explainer Video
                </button>
                <button className=" rounded-md border-2 border-white px-5 py-2">
                  Lightpaper
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-green-800 w-1/2 h-44">
          <Image src={fVid}></Image>
        </div>
      </div>

      {/* another */}
      <div className="py-24 bg-vid flex justify-evenly  w-screen">
        <div className="bg-green-800 w-2/5 h-44">
          <Image src={fVid}></Image>
        </div>
        <div className=" flex justify-center items-center w-1/2 h-96">
          <div className="rounded-md px-4 py-5 bg-glass border-2 border-cyan-700">
            <div className=" flex flex-col justify-start items-start text-white py-4 px-4">
              <h1 className="pb-14 text-3xl">No More Donations</h1>
              <p className=" text-lg">
                In 2020 game-streaming revenue reached over $9.2bln - at this
                point a successful streamer is one of web 3.0 biggest assets
                <br />
                <br /> The market has grown tremendowsly, but the old financial
                model still revolves around donations.
                <br /> <br />
                We are shutting down the “charity” model where streamers make
                money on the goodwill of the audience.
              </p>
              <div className="pt-8 flex justify-center items-center space-x-14">
                <button className="link rounded-md border-2 border-cyan-700 px-2 py-2">
                  Further in Lightpaper
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* 4 globes neemble */}
      <div className="py-24 bg-vid flex justify-evenly  w-screen">
        <div className=" flex justify-center items-center w-1/2 h-96">
          <div className="rounded-md px-4 py-5 bg-glass border-2 border-cyan-700">
            <div className=" flex flex-col justify-start items-start text-white py-4 px-4">
              <h1 className="pb-14 text-3xl">Introducing Streamer Coin</h1>
              <p className=" text-lg">
                Every streamer mints 11.3 millions of his personal streamer
                tokens and viewers are able to access streamer tokens on
                Neebmle-swap
                <br />
                <br />
                Token utility and values are measured by: revenue generated by
                the streamer, hours of watched streams, # of unique viewers,
                followers etc.
              </p>
              <div className="pt-8 flex justify-center items-center space-x-14">
                <button className=" rounded-md border-2 border-white px-5 py-2">
                  More on this in neemble whitepaper
                </button>
                <button className="bg-green-700 rounded-md border-2 border-green-400 px-5 py-2">
                  Buy NMBL
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className=" w-2/5 h-44">
          <Image src={globes}></Image>
        </div>
      </div>

      {/* 4 cards  */}
      <div className="py-24 bg-vid flex justify-evenly  w-screen">
        <div className=" w-2/5 h-44">
          <Image src={cardImage}></Image>
        </div>
        <div className=" flex justify-center items-center w-1/2 h-96">
          <div className="rounded-md px-4 py-5 bg-glass border-2 border-cyan-700">
            <div className=" flex flex-col justify-start items-start text-white py-4 px-4">
              <h1 className="pb-14 text-3xl">
                Introducing NFT Subscription Passes
              </h1>
              <p className=" text-lg">
                NFT-Passes will let holders be elligible for: small and big
                streamer token airdrops, NMBL token airdrops, NFT pass staking,
                streamer token staking, white-list spots to private streamer
                token sales, access to the streamer’s alpha chat and more...
                <br />
                <br />
                Passes have 25 levels, and Mana is required to upgrade your
                NFT-passes, mana is used to activate your rewards
                <br />
                <br />
                In stead of the charity and ads based monetization model we aim
                to turn every streamer into a free-to-watch, netflix-like
                subscription.
              </p>
              <div className="pt-8 flex justify-center items-center space-x-14">
                <button className="link rounded-md border-2 border-cyan-700 px-2 py-2">
                  Litepaper link: NFT Pass Subscription Model
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* last video gaming */}

      <div className="py-24 bg-vid flex justify-evenly  w-screen">
        <div className=" flex justify-center items-center w-1/2 h-96">
          <div className="rounded-md px-4 py-5 bg-glass border-2 border-cyan-700">
            <div className=" flex flex-col justify-start items-start text-white py-4 px-4">
              <h1 className="pb-14 text-3xl">Introducing Team Streams</h1>
              <p className="pb-8 text-lg">
                This has never been done. Even though most streamed games are
                team-games and teams can have multiple streamers.
                <br />
                <br />
                Team Streams let you access a connected stream between 2 or more
                streamers
                <br />
                <br />
                Your favorite streamers could team stream on 1 live-feed, and
                our streaming platform letting you immerse into the team-play
                <br />
                <br />
                Your favorite esports teams can stream their practice games with
                voice or webcameras on giving you a full emmersion into their
                team-play
              </p>
            </div>
          </div>
        </div>
        <div className=" w-2/5 h-44">
          <Image src={gameTeam}></Image>
        </div>
      </div>

      {/* promo 1  */}
      <div className="py-24 bg-vid flex justify-evenly  w-screen">
        <div className=" w-2/5 h-44">
          <Image src={promo1}></Image>
        </div>
        <div className=" flex justify-center items-center w-1/2 h-96">
          <div className="rounded-md px-4 py-5 bg-glass border-2 border-cyan-700">
            <div className=" flex flex-col justify-start items-start text-white py-4 px-4">
              <h1 className="pb-14 text-3xl">
                Introducing NFT Subscription Passes
              </h1>
              <p className=" text-lg">
                Neemble is a PC and Mobile first platform
                <br />
                <br />
                We want mobile users to have access to all neemble platform has
                to offer.
                <br />
                <br />
                Mobile streaming platform will be released with Neemble Beta
                release
              </p>
              <div className="w-full pt-8 flex justify-center items-center">
                <div className="px-10">
                  <Image width={180} height={50} src={apple} />
                </div>
                <div className="px-10">
                  <Image width={180} height={50} src={google} />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* promo 2 */}
      <div className="py-24 bg-vid flex justify-evenly  w-screen">
        <div className=" flex justify-center items-center w-1/2 h-96">
          <div className="rounded-md px-4 py-5 bg-glass border-2 border-cyan-700">
            <div className=" flex flex-col justify-center items-center text-white py-4 px-4">
              <h1 className="pb-14 text-3xl">Neemble Clips</h1>
              <p className="pb-8 text-center text-lg">
                0-120 second Horrizontal Tik-Tok Like Clips . Swipe up to see
                next clip, discover moments of new up and coming streamers
                <br />
                <br />
                Streamer meme moments, amazing highlighted plays.
                <br />
                <br />
                Short, interesting, and nimble
              </p>
            </div>
          </div>
        </div>
        <div className=" w-2/5 h-44">
          <Image src={promo2}></Image>
        </div>
      </div>
    </>
  );
}
